### ISSUE TITLE
UnicodeDecodeError when URL contains non-latin unicode characters

### ISSUE THREAD

**Issue by odednoam** [Khan/gae_mini_profiler#48]
When URL string contains non-latin UTF-8 characters around its 26th byte, 'url_short' is created in such way that the UTF-8 string is trimmed mid-character. The created string is invalid and this causes an exception to be thrown when serializing the string.

    'utf8' codec can't decode byte 0xd7 in position 25: invalid continuation byte
    Traceback (most recent call last):
      File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
        rv = self.handle_exception(request, response, e)
      File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
        rv = self.router.dispatch(request, response)
      File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
        return route.handler_adapter(request, response)
      File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
        return handler.dispatch()
      File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
        return self.handle_exception(e, self.app.debug)
      File "/python27_runtime/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
        return method(*args, **kwargs)
      File "/base/data/home/apps/s~fbarguing/0-3-130308-432dcc0.365808385936785782/gae_mini_profiler/profiler.py", line 222, in get
        dict_request_stats[property] = unicode(request_stats.__getattribute__(property), 'utf-8')
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xd7 in position 25: invalid continuation byte
    
For example, try the URL `http://myapp.appspot.com/%D7%94%D7%A7%D7%98%D7%A0%D7%AA-%D7%94%D7%92%D7%99%D7%A8%D7%A2%D7%95%D7%9F-%D7%A9%D7%9C-%D7%9E%D7%93%D7%99%D7%A0%D7%AA-%D7%99%D7%A9%D7%A8%D7%90%D7%9C/1`

I've implemented the solution, you can pull it from my repository at https://github.com/odednoam/gae_mini_profiler .

**Comment by benjaminjkraft** [comment]
Apologies for the very delayed response to this issue.  It looks like the offending line of code was removed entirely by aef9d594b, and the issue appears fixed to me, so I'm going to close this -- feel free to open a new issue if you still find problems.
