### ISSUE TITLE
thread safe issue with dev_appserver and 1.8.1

### ISSUE THREAD

**Issue by garethreakes** [Khan/gae_mini_profiler#57]
Hi,

This is simliar to this issue (https://github.com/kamalgill/flask-appengine-template/issues/36). Its different though in that its fine once deployed. Its also fine locally with threadsafe set to false. It fails on a ramdom request on pages that have multiple requests being submitted. Here is the stack trace:

Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 224, in Handle
    for chunk in result:
  File "/Users/garethreakes/github/3rings/threeRingsSite/gae_mini_profiler/profiler.py", line 542, in __call__
    for value in result:
  File "/Users/garethreakes/github/3rings/threeRingsSite/gae_mini_profiler/profiler.py", line 418, in profile_start_response
    yield result_fxn_wrapper(result.next)
  File "/Users/garethreakes/github/3rings/threeRingsSite/gae_mini_profiler/instrumented_profiler.py", line 71, in run
    return self.c_profile.runcall(lambda *args, **kwargs: fxn(), None, None)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cProfile.py", line 149, in runcall
    return func(*args, **kw)
  File "/Users/garethreakes/github/3rings/threeRingsSite/gae_mini_profiler/instrumented_profiler.py", line 71, in <lambda>
    return self.c_profile.runcall(lambda *args, **kwargs: fxn(), None, None)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/appstats/recording.py", line 1276, in appstats_wsgi_wrapper
    result = app(environ, appstats_start_response)
  File "/Users/garethreakes/github/3rings/threeRingsSite/gae_mini_profiler/appstats_profiler.py", line 148, in wrapped_appstats_app
    return app(environ, start_response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/django-1.4/django/core/handlers/wsgi.py", line 253, in __call__
    start_response(status, response_headers)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/ext/appstats/recording.py", line 1273, in appstats_start_response
    return start_response(status, headers, exc_info)
  File "/Users/garethreakes/github/3rings/threeRingsSite/gae_mini_profiler/profiler.py", line 518, in profiled_start_response
    return start_response(status, headers, exc_info)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 156, in _StartResponse
    (_GetTypeName(value), value, name))
InvalidResponseError: header values must be str, got 'NoneType' (None) for 'X-MiniProfiler-Id'

I have happy to have a look at this if someone could point me in the right direction.

Cheers,

Gareth

**Comment by benjaminjkraft** [comment]
Sounds like this is also fixed for the same reason as #66; feel free to reopen if that's not the case.
